FirstProject/FirstProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

import MyProfile.urls as MyProfile
from MyProfile import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.homepage),
    url(r'^MyProfile/', include(MyProfile, namespace="MyProfile"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

FirstProject/MyProfile/urls.py
from django.conf.urls import url
from . import views
app_name = "MyProfile"
urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^homepage/$', views.homepage, name='homepage'),
    url(r'^portofolio/$', views.portofolio, name="portofolio"),
    url(r'^guestbook/$', views.guestbook, name="guestbook"),
]

lab_1/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

lab_2/urls.py
from django.urls import path
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from lab_1.views import index as index_lab1


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^lab-1/', include('lab_1.urls')),
    re_path(r'^lab-2/', include('lab_2.urls')),
    re_path(r'^$', index_lab1, name='index')
]

FirstProject/MyProfile/models.py
from django.db import models

# Create your models here.

lab_1/models.py
from django.db import models

# Create your models here.

lab_2/models.py
from django.db import models

# Create your models here.

FirstProject/MyProfile/views.py
from django.shortcuts import render
from django.http import HttpResponse


def homepage(request):
    return render(request, "Homepage.html", {})

def portofolio(request):
    return render(request, "Portofolio.html", {})

def guestbook(request):
    return render(request, "Guest-book.html", {})

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
# Enter your name here
mhs_name = ['Mohammad Wildan Yanuar', 'Muhammad Faishal Ammar Wibowo', 'Wall'] # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = [date(1999, 1, 27), date(1999, 1, 27), date(1993, 1, 27)] #TODO Implement this, format (Year, Month, Date)
npm = [1706043973, 1706043973, 000000000] # TODO Implement this
hobby = ['sleeping', 'reading', 'standing']
# Create your views here.
def index(request):
    response = {'name0': mhs_name[0], 'age0': calculate_age(birth_date[0].year), 'npm0': npm[0], 'hobby0' : hobby[0],
                'name1': mhs_name[1], 'age1': calculate_age(birth_date[1].year), 'npm1': npm[1], 'hobby1' : hobby[1],
                'name2': mhs_name[2], 'age2': calculate_age(birth_date[2].year), 'npm2': npm[2], 'hobby2' : hobby[2]}
    return render(request, 'homepage.html', response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

lab_2/views.py
from django.shortcuts import render
from lab_1.views import mhs_name, birth_date

#TODO Implement
#Create a content paragraph for your landing page:
landing_page_content = ''

def index(request):
    response = {'name': mhs_name, 'content': landing_page_content}
    return render(request, 'index_lab2.html', response)

FirstProject/templates/Guest-book.html
{% extends "header.html" %}

{% block head %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Guest Book</title>
{% endblock%}

{% block body %}

<div class="content-d">
    <div class="title">
        <h1>
            GUEST BOOK
        </h1>
    </div>
    <div class="input-form">
        <form>
            <div class="form-group">
                <label for="exampleFormControlInput1" class="input-label">Name:</label>
                <input type="text" class="form-control" placeholder="Name">
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput1" class="input-label">Date:</label>
                <input type="date" class="form-control">
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput1" class="input-label">Email address:</label>
                <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput1" class="input-label">Subject:</label>
                <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Subject">
            </div>
            <div class="form-group">
                <label for="exampleFormControlTextarea1" class="input-label">Message:</label>
                <textarea class="form-control" id="textarea" rows="3" placeholder="Message"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
</div>
{% endblock %}

FirstProject/templates/Homepage.html
{% extends "header.html" %}
{% block head %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Mohammad Wildan Yanuar</title>
{% endblock %}

{% block body %}

<div class="header">
    <div class="background"></div>
    <div class="img-me">
        <img src="https://www.imageupload.co.uk/images/2018/09/27/foto.png" alt="">
    </div>
    <div class="name">
        <h1>i'm yayan</h1>
        <h3>information system student<br>University of Indonesia</h3>
    </div>
    <div class="introduction">
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique neque fugiat temporibus, sit
            reiciendis, nostrum, rem iusto officiis ad soluta doloremque assumenda in architecto. Pariatur.</p>
    </div>
    <a class="btn" href="#">contact</a>
</div>
<div class="content-a">
    <div class="title">
        <h1>1. skill</h1>
    </div>
    <div class="skill">
        <ul>
            <li>
                <h3>HTML</h3>
                <span class="bar">
                    <span class="html">
                    </span>
                </span>
            </li>
            <li>
                <h3>CSS</h3>
                <span class="bar">
                    <span class="css">
                    </span>
                </span>
            </li>
            <li>
                <h3>python</h3>
                <span class="bar">
                    <span class="python">
                    </span>
                </span>
            </li>
        </ul>
    </div>
</div>
<div class="content-b">
    <div class="title">
        <h1>2. PORTOFOLIO</h2>
    </div>
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big1.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big2.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big3b6bba.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big4.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big5.jpg" alt="">
</div>
<div class="content-c">
    <div class="title">
        <h1>3. contact</h1>
    </div>
    <div class="contact">
        <ul>
            <li>
                <img src="https://www.imageupload.co.uk/images/2018/09/27/Phone.png" alt="">
                <p>081286227658</p>
            </li>
            <li>
                <a href="https://www.linkedin.com/in/mohammadwildanyanuar/" class="contact-b" id="contact2b" style="text-decoration:none">
                    <img src="https://www.imageupload.co.uk/images/2018/09/27/linkin.png" alt="">
                    <br>
                    Mohammad Wildan Yanuar
                </a>
            </li>
            <li>
                <a href="https://www.facebook.com/mohammadwildan.yanuar" class="contact-b" id="contact3b" style="text-decoration:none">
                    <img src="https://www.imageupload.co.uk/images/2018/09/27/facebook.png" alt="">
                    <br>
                    Mohammad Wildan Yanuar
                </a>
            </li>
            <li>
                <a href="https://www.instagram.com/mohammadwildany/" class="contact-b" id="contact4b" style="text-decoration:none">
                    <img src="https://www.imageupload.co.uk/images/2018/09/27/instagram.png" alt="">
                    <br>
                    mohammadwildany
                </a>
            </li>
        </ul>
    </div>
</div>
</div>

{% endblock %}

FirstProject/templates/Portofolio.html
{% extends "header.html" %}
<!DOCTYPE html>
<html lang="en">

{% block head %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Portofolio</title>
{% endblock %}

{% block body %}
<div class="content-b">
    <div class="title">
        <h1>2. PORTOFOLIO</h2>
    </div>
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big1.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big2.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big3b6bba.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big4.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big5.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big6.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big7.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big8.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big9.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big10.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big11.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big12.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big13.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big14.jpg" alt="">
    <img class="big" src="https://www.imageupload.co.uk/images/2018/09/27/big16.jpg" alt="">
</div>
</div>
{% endblock %}

FirstProject/templates/header.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <link href="{% static 'style-coba.css' %}" rel="stylesheet">
    {% block head %}
    {% endblock%}
</head>

<body>
    <div class="wrapper">
        <div class="menu">
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'MyProfile:homepage' %}">
                            <img src="https://www.imageupload.co.uk/images/2018/09/27/Design.png" alt="">
                        </a>
                    </li>
                    <li>
                        <a href="#">About Me</a>
                    </li>
                    <li>
                        <a href="{% url 'MyProfile:portofolio' %}">Portofolio</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                    <li>
                        <a href="{% url 'MyProfile:guestbook' %}">Guest Book</a>
                    </li>
                </ul>
            </nav>
        </div>
        {% block body %}
        {% endblock %}
</body>

</html>

lab_1/templates/Guest-book.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Guest Book</title>
    <link href="style-coba.css" rel="stylesheet" type="text/css">
</head>

<body>
    <div class="wrapper">
        <div class="menu">
            <nav>
                <ul>
                    <li>
                        <a href="#">
                            <img src="Design.png" alt="">
                        </a>
                    </li>
                    <li>
                        <a href="#">About Me</a>
                    </li>
                    <li>
                        <a href="#">Portofolio</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                    <li>
                        <a href="#">Guest Book</a>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="content-d">
            <div class="title">
                <h1>
                    GUEST BOOK
                </h1>
            </div>
            <div class="input-form">
                <form>
                    <div class="form-group">
                        <label for="exampleFormControlInput1" class="input-label">Name:</label>
                        <input type="text" class="form-control" placeholder="Name">
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlInput1" class="input-label">Date:</label>
                        <input type="date" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlInput1" class="input-label">Email address:</label>
                        <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlInput1" class="input-label">Subject:</label>
                        <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Subject">
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1" class="input-label">Message:</label>
                        <textarea class="form-control" id="textarea" rows="3" placeholder="Message"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>

</body>

</html>

lab_1/templates/coba.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="style-coba.css" rel="stylesheet" type="text/css">
    <title>Mohammad Wildan Yanuar</title>
</head>

<body>
    <div class="wrapper">
        <div class="menu">
            <nav>
                <ul>
                    <li>
                        <a href="#">
                            <img src="Design.png" alt="">
                        </a>
                    </li>
                    <li>
                        <a href="#">About Me</a>
                    </li>
                    <li>
                        <a href="#">Portofolio</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                    <li>
                        <a href="#">Guest Book</a>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="header">
            <div class="background"></div>
            <div class="img-me">
                <img src="foto.png" alt="">
            </div>
            <div class="name">
                <h1>i'm yayan</h1>
                <h3>information system student<br>University of Indonesia</h3>
            </div>
            <div class="introduction">
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique neque fugiat temporibus, sit
                    reiciendis, nostrum, rem iusto officiis ad soluta doloremque assumenda in architecto. Pariatur.</p>
            </div>
            <a class="btn" href="#">contact</a>
        </div>
        <div class="content-a">
            <div class="title">
                <h1>1. skill</h1>
            </div>
            <div class="skill">
                <ul>
                    <li>
                        <h3>HTML</h3>
                        <span class="bar">
                            <span class="html">
                            </span>
                        </span>
                    </li>
                    <li>
                        <h3>CSS</h3>
                        <span class="bar">
                            <span class="css">
                            </span>
                        </span>
                    </li>
                    <li>
                        <h3>python</h3>
                        <span class="bar">
                            <span class="python">
                            </span>
                        </span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="content-b">
            <div class="title">
                <h1>2. PORTOFOLIO</h2>
            </div>
            <img class="big" src="img/big1.JPG" alt="">
            <img class="big" src="img/big2.JPG" alt="">
            <img class="big" src="img/big3.JPG" alt="">
            <img class="big" src="img/big4.JPG" alt="">
            <img class="big" src="img/big5.JPG" alt="">
        </div>
        <div class="content-c">
            <div class="title">
                <h1>3. contact</h1>
            </div>
            <div class="contact">
                <ul>
                    <li>
                        <img src="Phone.png" alt="">
                        <p>081286227658</p>
                    </li>
                    <li>
                        <a href="https://www.linkedin.com/in/mohammadwildanyanuar/" class="contact-b" id="contact2b"
                            style="text-decoration:none">
                            <img src="linkin.png" alt="">
                            <br>
                            Mohammad Wildan Yanuar
                        </a>
                    </li>
                    <li>
                        <a href="https://www.facebook.com/mohammadwildan.yanuar" class="contact-b" id="contact3b" style="text-decoration:none">
                            <img src="facebook.png" alt="">
                            <br>
                            Mohammad Wildan Yanuar
                        </a>
                    </li>
                    <li>
                        <a href="https://www.instagram.com/mohammadwildany/" class="contact-b" id="contact4b" style="text-decoration:none">
                            <img src="instagram.png" alt="">
                            <br>
                            mohammadwildany
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

</body>

</html>

lab_1/templates/main-page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="style.css" rel="stylesheet" type="text/css">
    <title>Mohammad Wildan Yanuar</title>
</head>

<body>
    <!-- Header -->

    <!-- Main -->
    <main id="main">
        <!--Section A-->
        <section id="section-a" class="grid">
            <div class="bg-image">
            </div>
            <div class="content-wrap-a">

                <div class="try1">
                    <img src="foto.png" alt="">
                </div>
                <div class="try2">
                    <h1 id="name">I'M YAYAN</h1>
                    <h3>INFORMATION SYSTEM STUDENT<br>UNIVERSITY OF INDONESIA</h3>
                </div>
                <div class="try3">
                    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti, illo porro sed repudiandae
                        odio
                        quibusdam necessitatibus quas nihil quia obcaecati?
                    </p>
                </div>
                <div class="try4">
                    <a href="#" class="btn">ABOUT ME</a>
                    <a href="#" class="btn">CONTACT</a>
                </div>
            </div>
        </section>
        <!--Section B-->
        <section id="section-b" class="grid">
            <div class="content-wrap-b">
                <h2>1. SKILL</h2>
                <h3>HTML</h3>
                <div class="line line1">60%</div>
                <h3>CSS</h3>
                <div class="line line1">50%</div>
                <h3>Django</h3>
                <div class="line line1">40%</div>
            </div>

        </section>
        <!--Section C-->
        <section id="section-c" class="grid">
            <div class="portofolio">
                <h2>2. PORTOFOLIO</h2>
                <img src="https://source.unsplash.com/random/200x200" alt="">
                <img src="https://source.unsplash.com/random/201x200" alt="">
                <img src="https://source.unsplash.com/random/202x200" alt="">
                <img src="https://source.unsplash.com/random/203x200" alt="">
            </div>

        </section>
        <!--Section D-->
        <section id="section-d" class="grid">
            <div class="content-wrap-d">
                <h2>3. CONTACT</h2>
                <div class="contact">
                    <ul>
                        <li>
                            <img src="Phone.png" alt="">
                            <p>081286227658</p>
                        </li>
                        <li>
                            <a href="https://www.linkedin.com/in/mohammadwildanyanuar/" class="contact-b" id="contact2b"
                                style="text-decoration:none">
                                <img src="linkin.png" alt="">
                                <br>
                                Mohammad Wildan Yanuar
                            </a>
                        </li>
                        <li>
                            <a href="https://www.facebook.com/mohammadwildan.yanuar" class="contact-b" id="contact3b"
                                style="text-decoration:none">
                                <img src="facebook.png" alt="">
                                <br>
                                Mohammad Wildan Yanuar
                            </a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/mohammadwildany/" class="contact-b" id="contact4b" style="text-decoration:none">
                                <img src="instagram.png" alt="">
                                <br>
                                mohammadwildany
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

        </section>

    </main>

</body>

</html>

lab_1/templates/portofolio.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Portofolio</title>
    <link href="style-coba.css" rel="stylesheet" type="text/css">
</head>

<body>
    <div class="wrapper">
        <div class="menu">
            <nav>
                <ul>
                    <li>
                        <a href="#">
                            <img src="Design.png" alt="">
                        </a>
                    </li>
                    <li>
                        <a href="#">About Me</a>
                    </li>
                    <li>
                        <a href="#">Portofolio</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                    <li>
                        <a href="#">Guest Book</a>
                    </li>
                </ul>
            </nav>
        </div>

        <div class="content-b">
            <div class="title">
                <h1>2. PORTOFOLIO</h2>
            </div>
            <img class="big" src="img/big1.JPG" alt="">
            <img class="big" src="img/big2.JPG" alt="">
            <img class="big" src="img/big3.JPG" alt="">
            <img class="big" src="img/big4.JPG" alt="">
            <img class="big" src="img/big5.JPG" alt="">
            <img class="big" src="img/big6.JPG" alt="">
            <img class="big" src="img/big7.JPG" alt="">
            <img class="big" src="img/big8.JPG" alt="">
            <img class="big" src="img/big9.JPG" alt="">
            <img class="big" src="img/big10.JPG" alt="">
            <img class="big" src="img/big11.JPG" alt="">
            <img class="big" src="img/big12.JPG" alt="">
            <img class="big" src="img/big13.JPG" alt="">
            <img class="big" src="img/big14.JPG" alt="">
            <img class="big" src="img/big15.JPG" alt="">
            <img class="big" src="img/big16.JPG" alt="">
        </div>
    </div>

</body>

</html>

lab_2/templates/description_lab2addon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body style="background-color: aqua">
    <h3 style="text-align: center">Hi all, This is my complete biodata</h3>
    <table align="center" style="text-align: center">
        {% for bio in bio_dict %}
            <tr>
                <td class="subject">{{ bio.subject }}</td>
                <td class="value">{{ bio.value }}</td>
            </tr>
        {% endfor %}
    </table>
    <br><br>
</body>

</html>

lab_2/templates/index_lab2.html
{% extends "base.html" %}
{% block content %}
<style>
    .center_screen {
        position: absolute;
        width: 500px;
        height: 50px;
        top: 50%;
        left: 50%;
        margin-left: -250px; /* margin is -0.5 * dimension */
        margin-top: -25px;
    }
</style>
<div class="center_screen">
    <p class="status" id="test">Hello, this is {{ name }}. {{ content }}.</p>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color: lightgray">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/lab-2/">Home</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/lab-2-addon/">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/lab-3/">Diary</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

templates/description_lab2addon.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hi all, This is my complete biodata</h3>
<table align="center" style="text-align: center">
    {% for bio in bio_dict %}
        <tr>
            <td class="subject">{{ bio.subject }}</td>
            <td class="value">{{ bio.value }}</td>
        </tr>
    {% endfor %}
</table>
<br><br>
{% endblock %}

templates/to_do_list.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hai semua, berikut adalah Catatan Harianku</h3>
<br><br>
<div class="row">
    <div class="col-md-6 col-xs-6">
        <table align="center" style="text-align: center">
            <tr>
                <th>Tanggal</th>
                <th>Yang akan dikerjakan</th>
            </tr>
            {% for diary_data in diary_dict %}
                <tr>
                    <td class="date">{{ diary_data.date }}</td>
                    <td class="activity">{{ diary_data.activity }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="col-md-6 col-xs-6">
        <form method="POST" action="add_activity/">
            {% csrf_token %}
            <table>
                <tr>
                    <td>
                        Tanggal
                    </td>
                    <td>
                        <input type="datetime-local" name="date" id="date" required="required"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        Kegiatan
                    </td>
                    <td>
                        <input type="text" name="activity" id="activity" size="25"/>
                    </td>
                </tr>
            </table>
            <button type="submit" class="button btn-success">Submit</button>
        </form>
    </div>
</div>
{% endblock %}